server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;

  gzip on;
  gzip_types text/css application/javascript image/svg+xml application/json;

  # Langue par défaut
  location = / {
    return 302 /fr/;
  }

  # Fichiers générés avec hash : cache long
  location /_next/static/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location /assets/ {
    expires 30d;
  }

  location / {
    try_files $uri $uri/ $uri.html =404;
  }

  error_page 404 /404.html;
}
