/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    news: News;
    players: Player;
    staff: Staff;
    clubs: Club;
    matches: Match;
    videos: Video;
    partners: Partner;
    'academy-categories': AcademyCategory;
    media: Media;
    'contact-messages': ContactMessage;
    'newsletter-subscribers': NewsletterSubscriber;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    news: NewsSelect<false> | NewsSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    clubs: ClubsSelect<false> | ClubsSelect<true>;
    matches: MatchesSelect<false> | MatchesSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'academy-categories': AcademyCategoriesSelect<false> | AcademyCategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en' | 'it') | ('fr' | 'en' | 'it')[];
  globals: {
    home: Home;
    pages: Page;
    standings: Standing;
    settings: Setting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    standings: StandingsSelect<false> | StandingsSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: 'fr' | 'en' | 'it';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * Généré depuis le titre si vide.
   */
  slug?: string | null;
  category: 'Match' | 'Avant-match' | 'Coupe' | 'Académie' | 'Club' | 'Partenaires';
  publishedAt: string;
  /**
   * Mis en avant en tête de l'accueil et des actualités.
   */
  featured?: boolean | null;
  cover: number | Media;
  excerpt: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Décrit l'image pour les lecteurs d'écran. Laisser vide si purement décorative.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    md?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    lg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xl?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: number;
  _order?: string | null;
  number: number;
  name: string;
  line: 'G' | 'D' | 'M' | 'A';
  /**
   * Ex. Latérale droite
   */
  position: string;
  nationality?: string | null;
  photo: number | Media;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  _order?: string | null;
  name: string;
  role: string;
  /**
   * Facultatif : un placeholder « Photo à venir » est affiché sinon.
   */
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clubs".
 */
export interface Club {
  id: number;
  name: string;
  crest?: (number | null) | Media;
  isUs?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches".
 */
export interface Match {
  id: number;
  label?: string | null;
  competition: 'league' | 'cup' | 'friendly';
  round?: number | null;
  kickoff: string;
  home: number | Club;
  away: number | Club;
  homeScore?: number | null;
  awayScore?: number | null;
  /**
   * Ex. « Match reporté ». Facultatif.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  _order?: string | null;
  title: string;
  thumbnail: number | Media;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  _order?: string | null;
  name: string;
  tier: 'main' | 'kit' | 'official' | 'academy';
  /**
   * Ex. « Face avant du maillot »
   */
  placement?: string | null;
  /**
   * Facultatif : le nom est affiché sinon.
   */
  logo?: (number | null) | Media;
  url?: string | null;
  showOnHome?: boolean | null;
  placeholder?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academy-categories".
 */
export interface AcademyCategory {
  id: number;
  _order?: string | null;
  /**
   * Ex. U15
   */
  code: string;
  /**
   * Ex. 2012-2013
   */
  years: string;
  focus: string;
  slots: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  status?: ('new' | 'in_progress' | 'done') | null;
  subject: 'Supporters' | 'Partenariat' | 'Presse' | 'Académie';
  name: string;
  email: string;
  company?: string | null;
  message?: string | null;
  locale?: string | null;
  internalNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  locale?: string | null;
  unsubscribed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Éditeur : gère le contenu. Administrateur : gère aussi les comptes.
   */
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'players';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null)
    | ({
        relationTo: 'clubs';
        value: number | Club;
      } | null)
    | ({
        relationTo: 'matches';
        value: number | Match;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'academy-categories';
        value: number | AcademyCategory;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  publishedAt?: T;
  featured?: T;
  cover?: T;
  excerpt?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  _order?: T;
  number?: T;
  name?: T;
  line?: T;
  position?: T;
  nationality?: T;
  photo?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  role?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clubs_select".
 */
export interface ClubsSelect<T extends boolean = true> {
  name?: T;
  crest?: T;
  isUs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches_select".
 */
export interface MatchesSelect<T extends boolean = true> {
  label?: T;
  competition?: T;
  round?: T;
  kickoff?: T;
  home?: T;
  away?: T;
  homeScore?: T;
  awayScore?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  thumbnail?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  tier?: T;
  placement?: T;
  logo?: T;
  url?: T;
  showOnHome?: T;
  placeholder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academy-categories_select".
 */
export interface AcademyCategoriesSelect<T extends boolean = true> {
  _order?: T;
  code?: T;
  years?: T;
  focus?: T;
  slots?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        md?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        lg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xl?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  status?: T;
  subject?: T;
  name?: T;
  email?: T;
  company?: T;
  message?: T;
  locale?: T;
  internalNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  locale?: T;
  unsubscribed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  heroPhotos: (number | Media)[];
  tagline?: string | null;
  band?: {
    line1?: string | null;
    line2?: string | null;
  };
  academy?: {
    text?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Ex. « Contenus à venir ». Laisser vide pour masquer.
   */
  videosNote?: string | null;
  newsletterText?: string | null;
  /**
   * Grille de 4 colonnes : chaque photo occupe 1 ou 2 colonnes et 1 ou 2 rangées.
   */
  gallery?:
    | {
        image: number | Media;
        cols?: ('1' | '2') | null;
        rows?: ('1' | '2') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  equipe: {
    title: string;
    intro: string;
    staffNote?: string | null;
  };
  calendrier: {
    title: string;
    intro: string;
  };
  classement: {
    title: string;
    intro: string;
  };
  actus: {
    title: string;
    intro: string;
  };
  academie: {
    title: string;
    intro: string;
    image?: (number | null) | Media;
    ctaTitle?: string | null;
  };
  partenaires: {
    title: string;
    intro: string;
    pitchTitle?: string | null;
    pitchText?: string | null;
    offers?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  contact: {
    title: string;
    intro: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Ordre des lignes = ordre du classement (glisser-déposer).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "standings".
 */
export interface Standing {
  id: number;
  note?: string | null;
  rows?:
    | {
        club: number | Club;
        played?: number | null;
        won?: number | null;
        drawn?: number | null;
        lost?: number | null;
        goalDiff?: number | null;
        points?: number | null;
        /**
         * Lettres V, N ou D, du plus ancien au plus récent. Ex. VVN
         */
        form?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  stadium: string;
  city: string;
  email: string;
  pressEmail?: string | null;
  /**
   * Ex. « Stade Didier Deschamps, Cap-d’Ail »
   */
  mapQuery: string;
  /**
   * Nécessite la configuration SMTP (variables d'environnement).
   */
  notificationEmail?: string | null;
  socials?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroPhotos?: T;
  tagline?: T;
  band?:
    | T
    | {
        line1?: T;
        line2?: T;
      };
  academy?:
    | T
    | {
        text?: T;
        image?: T;
      };
  videosNote?: T;
  newsletterText?: T;
  gallery?:
    | T
    | {
        image?: T;
        cols?: T;
        rows?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  equipe?:
    | T
    | {
        title?: T;
        intro?: T;
        staffNote?: T;
      };
  calendrier?:
    | T
    | {
        title?: T;
        intro?: T;
      };
  classement?:
    | T
    | {
        title?: T;
        intro?: T;
      };
  actus?:
    | T
    | {
        title?: T;
        intro?: T;
      };
  academie?:
    | T
    | {
        title?: T;
        intro?: T;
        image?: T;
        ctaTitle?: T;
      };
  partenaires?:
    | T
    | {
        title?: T;
        intro?: T;
        pitchTitle?: T;
        pitchText?: T;
        offers?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        title?: T;
        intro?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "standings_select".
 */
export interface StandingsSelect<T extends boolean = true> {
  note?: T;
  rows?:
    | T
    | {
        club?: T;
        played?: T;
        won?: T;
        drawn?: T;
        lost?: T;
        goalDiff?: T;
        points?: T;
        form?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  stadium?: T;
  city?: T;
  email?: T;
  pressEmail?: T;
  mapQuery?: T;
  notificationEmail?: T;
  socials?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}